[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cats = { path = "../cats" }
tokio = { version = "1.19.2", features = ["full"] }
